### ISSUE TITLE
Ruby 2.6 Sodium Error - Can't Use Discordrb

### ISSUE THREAD

**Issue by nhillsdonuk** [shardlab/discordrb#112]
# Summary

The error I am receiving is:
/usr/share/gems/gems/discordrb-3.4.0/lib/discordrb/voice/sodium.rb:6:in `<module:Sodium>': uninitialized constant Discordrb::Voice::Sodium::FFI (NameError)

I get this having installed Ruby 2.6. I have reinstalled all ruby components, cleared and rebundled, every possible step (other than rebuilding the code running box) and cannot get this to operate. Any advice as to what I must be doing wrong would be greatly appreciated, or, potentially what to fix if this is indeed a bug.
---

## Environment

**Ruby version:**

ruby 2.6.7p197 (2021-04-05 revision 67941) [x86_64-linux]

**Discordrb version:**

*** LOCAL GEMS ***

discordrb (3.4.0)
discordrb-webhooks (3.3.0)

**Comment by darkstego** [comment]
I am getting similar issue when using ruby 3.0.3. If I switch to 2.7.4 it works fine.

**Comment by swarley** [comment]
This issue was due to a quirk with CentOS and using system ruby. If possible try using a version manager and reinstalling your bundle. Alternatively, ensure that your gems, cache, etc from your previous version is not still on your system after upgrade
