### ISSUE TITLE
a1083b0b944700f582356fec3babd3fe6804c2ca breaks Member.modify_roles

### ISSUE THREAD

**Issue by jubishop** [shardlab/discordrb#118]
# Summary

If I call `modify_roles` once, adding some roles, and then I call it again, adding different roles, the roles I added the first time will be removed.  This only begins as of a1083b0b944700f582356fec3babd3fe6804c2ca.  If I roll back and use the previous commit, I'm fine.

---

## Environment

Heroku, Ruby 3.0.2.  Repros on Heroku and my own machine.

**Discordrb version:**

Gems included by the bundle:
  * addressable (2.8.0)
  * ballchasing (1.0)
  * concurrent-ruby (1.1.9)
  * core (1.17)
  * csv (3.2.2)
  * datacache (1.2)
  * date (3.2.2)
  * discordrb (3.4.2 f9a94c9)
  * discordrb-webhooks (3.4.2 f9a94c9)
  * domain_name (0.5.20190701)
  * duration (1.6)
  * event_emitter (0.2.6)
  * ffi (1.15.5)
  * ffi-compiler (1.0.1)
  * http (5.0.4)
  * http-accept (1.7.0)
  * http-cookie (1.0.4)
  * http-form_data (2.3.0)
  * json (2.6.1)
  * jubibot (1.4)
  * linguistics (2.1.0)
  * llhttp-ffi (0.4.0)
  * loggability (0.18.2)
  * mime-types (3.4.1)
  * mime-types-data (3.2022.0105)
  * netrc (0.11.0)
  * opus-ruby (1.0.1)
  * pg (1.2.3)
  * public_suffix (4.0.6)
  * rake (13.0.6)
  * rest-client (2.1.0)
  * rlranks (1.0)
  * rstruct (1.5)
  * single-instance (0.2)
  * steam (1.4)
  * unf (0.1.4)
  * unf_ext (0.0.8)
  * websocket (1.2.9)
  * websocket-client-simple (0.5.1)
  * yaml (0.2.0)

**Comment by swarley** [comment]
Could you share some code for repro please? If you code looks something like this you may be encountering a cache issue
```ruby
member = event.author
member.modify_roles([add_id])
member.modify_roles([], [remove_id])
```

**Comment by jubishop** [comment]
No, each happen from their own independent event.  The first adds some
roles, the second adds some different ones and the ones from the first
round are removed.  

cheers,
  - Justin Bishop <http://jubishop.com>

On January 10, 2022, GitHub Notifications ***@***.***>
wrote:
> Could you share some code for repro please? If your code looks
> something like this you may be encountering a cache issue
>
> member = event.author member.modify_roles([add_id])
> member.modify_roles([], [remove_id])

—
Reply to this email directly, view it on GitHub
<https://github.com/shardlab/discordrb/issues/118#issuecomment-
1009186449>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAADG3KOGMQ6AZC72ADOSMLUVMNOVANCNFSM5LUITPPA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
