### ISSUE TITLE
Test/Remove group channel methods?

### ISSUE THREAD

**Issue by Daniel-Worrall** [shardlab/discordrb#16]
https://github.com/shardlab/discordrb/blob/main/lib/discordrb/api/channel.rb#L334-L400

These API methods were added by myself and at least one of them will only work with a user token.

They should be revisited and tested to comply with the up to date API

**Comment by kaine119** [comment]
These methods do still work, but not to add the bot itself into the group DM. Instead, they allow an application to create a group DM as a sort of room (probably for games as mentioned [here](https://discord.com/developers/docs/resources/user#create-group-dm)) that the application can then manage and close as needed. Creating and adding members requires bearer tokens from a separate OAuth login with the `gdm.join` scope.
