### ISSUE TITLE
How to add role to someone

### ISSUE THREAD

**Issue by sai1024** [shardlab/discordrb#173]
hi, I want to add role to someone,

py code:

```
from discord.ext import commands
from discord.utils import get

bot = commands.Bot(command_prefix='!')

@bot.command(pass_context=True)
@commands.has_role("Admin") # This must be exactly the name of the appropriate role
async def addrole(ctx):
    member = ctx.message.author
    role = get(member.server.roles, name="Test")
    await bot.add_roles(member, role)
```

ruby?

**Comment by PixeLInc** [comment]
You're going to have to be a bit more specific than that.

In what context do you want to do so?
What have you tried?

Have you read the docs? (https://drb.shardlab.dev/main/Discordrb/Member.html#add_role-instance_method)

**Comment by sai1024** [comment]
> https://drb.shardlab.dev/main/Discordrb/Member.html#add_role-instance_method

sorry, I want to from discord bot invite user to private channel，so I try to add role，but role param i dont't know how to definition， I try code invite member to private channel:
```
Discordrb::API::Channel.add_group_user("Bot token", private_channel_id, member_id)
```
error:
The bot doesn't have the required permission to do this! (Discordrb::Errors::NoPermission)

**Comment by swarley** [comment]
If you're the owner of the server the bot is not able to modify your roles. Is this what you're trying to do? But also it's probably better to use non Discordrb::API methods if you're writing an interactive bot.

Something like event.author.add_role(...)` is going to be a much friendlier path for you

**Comment by sai1024** [comment]
> If you're the owner of the server the bot is not able to modify your roles. Is this what you're trying to do? But also it's probably better to use non Discordrb::API methods if you're writing an interactive bot.
> 
> Something like `event.author.add_role(...)` is going to be a much friendlier path for you

hi, Is there a specific spelling? I don't know role params to write.

I try this code:
```
Discordrb::API::Channel.update_permission
```
is it okay？，

**Comment by sai1024** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/56356960/184911550-56fc48d0-d57d-49a3-b6c7-4d81b2312d79.png">

The bot doesn't have the required permission to do this! (Discordrb::Errors::NoPermission)

**Comment by sai1024** [comment]
I started to try `add_role` method：

https://www.rubydoc.info/github/meew0/discordrb/Discordrb/Member#add_role-instance_method

I don't know how to define role parameters， thanks

**Comment by sai1024** [comment]
sorry, I am a newbie
```
Parameters:

role The role(s), or their ID(s), to add.
```

add_role([1009016039440388137]) ?

**Comment by swarley** [comment]
Yes, that is the correct usage. I'm fairly sure you're attempting to modify the roles of the server owner which is not possible. If you want more immediate support you might have better luck in our discord server https://discord.gg/discord-api. #ruby_discordrb
