### ISSUE TITLE
We could use a release for rubygems.

### ISSUE THREAD

**Issue by peterdeweese** [shardlab/discordrb#201]
The last in rubygems is [3.4.0](https://rubygems.org/gems/discordrb/versions/3.4.0) - December 06, 2020

There have been numerous changes since. With the gap of time and likely minor incompatibilities, I think we should release 3.5.0.

**Comment by ddavison** [comment]
I've pushed https://rubygems.org/gems/discordrb-dj temporarily until the Maintainers can get to this.

```ruby
source 'https://rubygems.org/'

gem 'discordrb-dj', '3.4.2'
```

**Comment by swarley** [comment]
I will get to this when I have time. I would prefer that other people do not create alternate packages and instead use a git lock in their bundle

**Comment by jasnow** [comment]
@peterdeweese - new release: https://rubygems.org/gems/discordrb/versions/3.5.0
