### ISSUE TITLE
Voice is broken

### ISSUE THREAD

**Issue by uscoders82** [shardlab/discordrb#208]
# Summary

IP Discovery is broken
---
IP Discovery is broken due to the breaking change that Discord released on March 20th. When I try to call `.voice_connect` it fails to establish a connection, but it worked perfectly fine before the change.
## Environment

NetBSD 9.3

**Ruby version:**

ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-netbsd]
**Discordrb version:**
  * discordrb (3.4.2)
  * discordrb-webhooks (3.4.2)
  * ffi (1.15.5)
  * opus-ruby (1.0.1)
  * rest-client (2.1.0)
  * websocket (1.2.9)
  * websocket-client-simple (0.6.1)

**Comment by mizunago** [comment]
Thanks, I was struggling with the same problem, but didn't know what was causing it.
