### ISSUE TITLE
400: bad request  - TTS should be string, not boolean, on `send_message`

### ISSUE THREAD

**Issue by pehrlich2** [shardlab/discordrb#220]
# Summary

I made a big mistake, and passed in arguments to `bot.send_message` as keyword args instead of positional.  This likely should have raised an error (TTS should not receive a hash type).  One way to solve this might be with Sorbet?

---

## Environment

osx 

**Ruby version:**

ruby 3.2.2

**Discordrb version:**

3.4.0

**Comment by swarley** [comment]
Sorry, we are unable to use sorbet at this time due to the fact that there is no support for windows. If this changes in the future we will reconsider.
We are considering the addition of RBS files but that will take a non trivial amount of time to do correctly
