### ISSUE TITLE
Please release 3.4.3

### ISSUE THREAD

**Issue by postmodern** [shardlab/discordrb#228]
It appears that you [fixed an important security bug](https://github.com/shardlab/discordrb/commit/91e13043ffa89227c3fcdc3408f06da237d28c95) recently, but haven't released a new gem version yet? Also, the latest gem version available on [rubygems.org](https://rubygems.org/gems/discordrb) is still 3.4.0.

**Comment by gracz21** [comment]
+1, the RubyGems version is veeeery outdated (from late 2020)

**Comment by swarley** [comment]
see you again in three years

**Comment by jasnow** [comment]
https://github.com/rubysec/ruby-advisory-db/pull/675 -- Updated advisory
