### ISSUE TITLE
Chore: Bump minimum to 3.0

### ISSUE THREAD

**Issue by Daniel-Worrall** [shardlab/discordrb#248]
Ruby 2.7 is EOL, Ruby 3.3 is realeased

We should bump minimum version to 3.0

**Comment by Dakurei** [comment]
I've rebased and updated the PRs you had me split to drop Ruby 2.7 support 👍

#216 and #217

**Comment by Daniel-Worrall** [comment]
Oh nice, sorry I had forgotten this was is place
