### ISSUE TITLE
Move webscoket-client-simple source

### ISSUE THREAD

**Issue by Daniel-Worrall** [shardlab/discordrb#250]
From bundle install
```
Post-install message from websocket-client-simple:
The development of this gem has moved to https://github.com/ruby-jp/websocket-client-simple
```

**Comment by PanisSupraOmnia** [comment]
No change is actually needed on our end, it's still the same thing on rubygems. The post-install message is just informational to let you know that the underlying source for websocket-client-simple has changed orgs, just like we did.
