### ISSUE TITLE
Ruby 3.3 deprecation warnings: base64 will no longer be part of the default gems

### ISSUE THREAD

**Issue by y-bonfire** [shardlab/discordrb#256]
# Summary

```
ruby/3.3.0/gems/discordrb-3.5.0/lib/discordrb/data.rb:18: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of discordrb-3.5.0 to add base64 into its gemspec.
```

I reported it as written like this.
>  Also contact author of discordrb-3.5.0 to add base64 into its gemspec.

I confirmed that there are no identical issues or pull requests through searching.

https://github.com/ruby/ruby/commit/6500f85927135901f365d2ba1186c5c4f2881f8e

I thought that adding this line would probably be the solution.
https://github.com/shardlab/discordrb/blob/main/discordrb.gemspec
```ruby
 spec.add_runtime_dependency 'base64'
```

---

## Environment

**Ruby version:**

```
ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
```

**Discordrb version:**

```
$ bundle list |grep discord
  * discordrb (3.5.0)
```

**Comment by PixeLInc** [comment]
fixed in merge of: https://github.com/shardlab/discordrb/pull/277
