### ISSUE TITLE
RL bucket depletion detected! Locking RL mutex for 3.859 seconds pre-emptively

### ISSUE THREAD

**Issue by tachikawa20** [shardlab/discordrb#41]
First of all, I would like to thank every contributor of this project, because it's been tremendously easy and very straight-forward to create a bot for Discord with your help.
 
The main goal of my bot is to list files and directories inside Google Drive, as well as downloading them. For that, I'm using the Google Drive V3 API.
 
I've already managed to do all that.
 
My problem is: I'm using *event.respond* to list files individually. Because of that, after 5 messages posted by the bot, it waits 4 seconds and then resumes. (This is what causes "RL bucket depletion detected! Locking RL mutex for 3.859 seconds pre-emptively")
 
If the limit of files displayed that I imposed is equal to 1000 files, and the 3 first lines of the message correspond to the header (composed by a greeting, the name of the bot, and the name of the current directory), as well as a line that marks the end of the directory: 
 
1000 + 3 + 1 = **1004 lines** *total*
&nbsp;
&nbsp;
 
So if it stops after 5 messages continously until the end of the directory,
**According to my calculations**
 
1004 / 5 = **200.8 times** *that the directory listing would halt*
 
200.8 * 4 = **803.2 seconds** *waiting* = **13.38 minutes** *waiting* 
&nbsp;
&nbsp;
 
**How can I overcome this?**
**How can I stop this from happening?**
 
Thank you for your time.
And again, you have been making such an amazing work! Carry on!

**Comment by PixeLInc** [comment]
That's discord rate-limiting for you, you can't stop it but you can work to not hit them.

What I personally would recommend is building a string with all of your file listings and sending it in one big message.
Do note though, that the message character limit is 2000 characters, with that said, you can make a system to chunk up messages in 2k increments and send those ones separately.

We have a utility you can use `Channel#split_send` which will do this for you, but of course, mind rate-limits if you're going to be sending over 5.
https://drb.shardlab.dev/main/Discordrb/Channel.html#split_send-instance_method

**Comment by tachikawa20** [comment]
I will definitly check it out. Thank you for answering so quickly.

**Comment by PixeLInc** [comment]
No problem!
Also if you didn't know, for more help or sometimes quicker help, feel free to join discord API (https://discord.gg/discord-api)
and there's a `#rb_discordrb` channel where there will normally be more people :)
