### ISSUE TITLE
Unable to return message reactions

### ISSUE THREAD

**Issue by ADawesomeguy** [shardlab/discordrb#42]
# Summary

The issue I'm facing is that `message.reactions` or `message::reactions` returns an empty array, even though there are reactions to the message. I can confirm the message is correct because `message::channels` and such return expected results. Please let me know if I'm doing something wrong!

---

## Environment

- `uname -sr`: `Linux 5.11.7-arch1-1`
- CPU: R7 3800X

**Ruby version:**

```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
```

**Discordrb version:**

```
*** LOCAL GEMS ***

discordrb (3.4.0)
discordrb-webhooks (3.3.0)
```

**Comment by PixeLInc** [comment]
I can't seem to repro this, I am on the latest (3.4.0) drb version as well.
Are you using intents?

```ruby
require 'discordrb'

bot = Discordrb::Commands::CommandBot.new token: 'token', client_id: 1234564789797987, prefix: ':>', intents: %i[servers server_messages server_message_reactions]

bot.command :message do |event, msg_id|
  message = event.channel.message(msg_id)
  puts(message.reactions)

  "reactions: #{message.reactions}"
end

bot.run
```

This correctly yields:
```
reactions: [#<Discordrb::Reaction:0x00007f59380ab200 @count=1, @me=false, @id=795019639745675264, @name="Sadge">, #<Discordrb::Reaction:0x00007f59380ab1d8 @count=1, @me=false, @id=422437560485412887, @name="No">]
```

Perhaps try the simplified version of code above and report back if that works?
If so, posting your code would be a great help to see any potential issues but that's about all I got.

**Comment by ADawesomeguy** [comment]
Thanks so much for the help and quick response! I'll check it out and post if it works. I think I may have not had the right intents.

**Comment by ADawesomeguy** [comment]
So, I was defining a message like `message = event.respond ""` and then trying to find what reactions it got with `puts message.reactions` but, and that didn't work, but for some reason `puts event.channel.message(message.id).reactions`. Is there a reason for this? Sorry, I'm really new to Ruby.

**Comment by Daniel-Worrall** [comment]
This is a common problem with querying messages that have just been sent. The message object is only accurate to the time when we receive the data, aka when you responded. 

If some time were to pass, users or your bot could then react to it and the data in your code will be different to what this message object holds. `Message#reactions` is data that is fetched from the message object, so you would have to fetch the message from the API to get an updated account.

This is a symptom of not caching Messages, and could be improved upon in future.

**Comment by ADawesomeguy** [comment]
Ah, I see. Thanks for all your help!
