### ISSUE TITLE
Deprecate alias Channel#send

### ISSUE THREAD

**Issue by Daniel-Worrall** [shardlab/discordrb#47]
Object#send is used by RubyMine debugger, and we shouldn't be overwriting any Object methods.

Also, turns out [I'm to blame](https://github.com/shardlab/discordrb/commit/b5e19dfc95491b4078c8c1b32142645d0852bf14#diff-f2f2d924d0a1e92b90bd01aeaf25d31286afc910ea5b97a98d269431112d939bR1048)

**Comment by swarley** [comment]
Not really sure about this one, needs further discussion. If anything, RubyMine should be using `__send__`
