### ISSUE TITLE
v9 api

### ISSUE THREAD

**Issue by 2vitor** [shardlab/discordrb#74]
i think discordrb should start migrating to discord api v9 (and releasing discordrb on it), since it is the most recent one

https://discord.com/developers/docs/reference#api-versioning-api-versions

**Comment by Daniel-Worrall** [comment]
> You can currently use the threads branch which has support for GW v9 and threads.

https://github.com/shardlab/discordrb/issues/52#issuecomment-892690271

https://github.com/shardlab/discordrb/tree/threads

You can test and give feedback by adding this into your Gemfile.
```rb
gem 'discordrb', github: 'shardlab/discordrb', branch: 'master'
```
