### ISSUE TITLE
`allowed_mentions` in webhook client results in Bad Request

### ISSUE THREAD

**Issue by Ruin0x11** [shardlab/discordrb#81]
# Summary

Using `allowed_mentions` with `Discordrb::Webhooks::Client.execute` fails with Bad Request.

```ruby
require "discordrb"
require "discordrb/webhooks"

client = Discordrb::Webhooks::Client.new(url: ENV["DISCORD_WEBHOOK_EN"])

begin
  client.execute do |builder|
    builder.content = "test"
    builder.allowed_mentions = Discordrb::AllowedMentions.new(parse: [])
  end
rescue RestClient::BadRequest => e
  puts e.response.body
end
```

Result:

```
{"allowed_mentions": ["Only dictionaries may be used in a ModelType"]}
```

---

## Environment

**Ruby version:**
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Discordrb version:**

  * discordrb (3.4.2 87ae658)
  * discordrb-webhooks (3.4.2 87ae658)

**Comment by swarley** [comment]
Thank you for the report! This has been merged into main and will make it into release when the 3.5.0 milestone is met. For the time being you can pin to this specific commit in bundle as such
```ruby
gem 'discordrb', github: 'shardlab/discordrb', ref: '79568216389529fe69fa1d429dd7f9772dcd0fb8'
```
