### ISSUE TITLE
wrong number of arguments (given 8, expected 3..7) in Bot.send_temporary_message

### ISSUE THREAD

**Issue by czuger** [shardlab/discordrb#93]
# Summary

When sending a temporary message with `send_temporary_message` the parameter , message_reference seems missing.

---

## Environment

**Ruby version:**

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**Discordrb version:**

discordrb (3.4.0)
discordrb-webhooks (3.3.0)

**Comment by czuger** [comment]
Note, this seems to be fixed in version 3.4.1 but last available gem version is 3.4.0 (however installing the gem directly from the repository is working).

**Comment by swarley** [comment]
Hello, it's a bit of a long time coming but I've recently updated the milestone for the next release. I hope to sort it all out in the coming weekend. You can track the status here https://github.com/shardlab/discordrb/milestone/2
